import { thisYear } from "./mock-shared";
import type { Order } from "./types";
import { products } from "./mock-products";
import { demoAddress } from "./mock-account";
import {
  shippingMethods,
  defaultCurrency,
  welcomeAppliedCoupon,
} from "./mock-checkout";

const adhdProduct = products.find(
  (product) => product.id === "prod-adhd-medication",
)!;
const matchaProduct = products.find(
  (product) => product.id === "prod-matcha-kit",
)!;
const herbalProduct = products.find((product) => product.id === "prod-herbal")!;
const bottleProduct = products.find((product) => product.id === "prod-bottle")!;

const matchaVariant = matchaProduct.variants[1]!;
const herbalVariant = herbalProduct.variants[1]!;
const bottleVariant = bottleProduct.variants[1]!;
const adhdVariant = adhdProduct.variants[0]!;

export const orders: Order[] = [
  {
    id: "ord-demo-003",
    number: "ORD-00003",
    status: "pending",
    financialStatus: "pending",
    fulfillmentStatus: "unfulfilled",
    createdAt: `${thisYear}-05-02T09:05:00.000Z`,
    updatedAt: `${thisYear}-05-02T09:05:00.000Z`,
    subtotalPrice: { amount: "198.00", currencyCode: defaultCurrency },
    totalPrice: { amount: "198.00", currencyCode: defaultCurrency },
    totalTax: { amount: "0.00", currencyCode: defaultCurrency },
    totalShipping: { amount: "0.00", currencyCode: defaultCurrency },
    currencyCode: defaultCurrency,
    lineItems: [
      {
        id: "ord-demo-003-line-1",
        productId: matchaProduct.id,
        productTitle: matchaProduct.title,
        variantId: matchaVariant.id,
        variantTitle: matchaVariant.title,
        quantity: 1,
        unitPrice: matchaVariant.price,
        totalPrice: { amount: "198.00", currencyCode: defaultCurrency },
        image: matchaProduct.featuredImage,
      },
    ],
    shippingAddress: demoAddress,
    billingAddress: demoAddress,
    shippingMethod: shippingMethods[2],
    customerId: "user-demo",
    appliedCoupons: [],
    loyaltyDelta: 60,
  },
  {
    id: "ord-demo-002",
    number: "ORD-00002",
    status: "processing",
    financialStatus: "paid",
    fulfillmentStatus: "unfulfilled",
    createdAt: `${thisYear}-04-27T14:12:00.000Z`,
    updatedAt: `${thisYear}-04-27T14:20:00.000Z`,
    processedAt: `${thisYear}-04-27T14:15:00.000Z`,
    subtotalPrice: { amount: "399.00", currencyCode: defaultCurrency },
    totalPrice: { amount: "419.00", currencyCode: defaultCurrency },
    totalTax: { amount: "0.00", currencyCode: defaultCurrency },
    totalShipping: { amount: "20.00", currencyCode: defaultCurrency },
    currencyCode: defaultCurrency,
    lineItems: [
      {
        id: "ord-demo-002-line-1",
        productId: adhdProduct.id,
        productTitle: adhdProduct.title,
        variantId: adhdVariant.id,
        variantTitle: adhdVariant.title,
        quantity: 1,
        unitPrice: adhdVariant.price,
        totalPrice: { amount: "399.00", currencyCode: defaultCurrency },
        image: adhdProduct.featuredImage,
      },
    ],
    shippingAddress: demoAddress,
    billingAddress: demoAddress,
    shippingMethod: shippingMethods[1],
    customerId: "user-demo",
    appliedCoupons: [],
    loyaltyDelta: 120,
  },
  {
    id: "ord-demo-001",
    number: "ORD-00001",
    status: "fulfilled",
    financialStatus: "paid",
    fulfillmentStatus: "fulfilled",
    createdAt: `${thisYear}-04-16T08:12:00.000Z`,
    updatedAt: `${thisYear}-04-18T12:30:00.000Z`,
    processedAt: `${thisYear}-04-16T08:15:00.000Z`,
    fulfilledAt: `${thisYear}-04-18T11:40:00.000Z`,
    subtotalPrice: { amount: "408.00", currencyCode: defaultCurrency },
    totalPrice: { amount: "387.20", currencyCode: defaultCurrency },
    totalTax: { amount: "0.00", currencyCode: defaultCurrency },
    totalShipping: { amount: "20.00", currencyCode: defaultCurrency },
    currencyCode: defaultCurrency,
    lineItems: [
      {
        id: "ord-demo-001-line-1",
        productId: matchaProduct.id,
        productTitle: matchaProduct.title,
        variantId: matchaVariant.id,
        variantTitle: matchaVariant.title,
        quantity: 2,
        unitPrice: matchaVariant.price,
        totalPrice: { amount: "192.00", currencyCode: defaultCurrency },
        image: matchaProduct.featuredImage,
      },
      {
        id: "ord-demo-001-line-2",
        productId: herbalProduct.id,
        productTitle: herbalProduct.title,
        variantId: herbalVariant.id,
        variantTitle: herbalVariant.title,
        quantity: 1,
        unitPrice: herbalVariant.price,
        totalPrice: { amount: "78.00", currencyCode: defaultCurrency },
        image: herbalProduct.featuredImage,
      },
      {
        id: "ord-demo-001-line-3",
        productId: bottleProduct.id,
        productTitle: bottleProduct.title,
        variantId: bottleVariant.id,
        variantTitle: bottleVariant.title,
        quantity: 1,
        unitPrice: bottleVariant.price,
        totalPrice: { amount: "138.00", currencyCode: defaultCurrency },
        image: bottleProduct.featuredImage,
      },
    ],
    shippingAddress: demoAddress,
    billingAddress: demoAddress,
    shippingMethod: shippingMethods[1],
    customerId: "user-demo",
    appliedCoupons: [welcomeAppliedCoupon],
    loyaltyDelta: 300,
    tracking: {
      carrier: "顺丰速运",
      trackingNumber: "SF1234567890",
    },
  },
  {
    id: "ord-demo-000",
    number: "ORD-00000",
    status: "fulfilled",
    financialStatus: "paid",
    fulfillmentStatus: "fulfilled",
    createdAt: `${thisYear}-03-22T10:05:00.000Z`,
    updatedAt: `${thisYear}-03-24T18:30:00.000Z`,
    processedAt: `${thisYear}-03-22T10:08:00.000Z`,
    fulfilledAt: `${thisYear}-03-24T16:40:00.000Z`,
    subtotalPrice: { amount: "399.00", currencyCode: defaultCurrency },
    totalPrice: { amount: "419.00", currencyCode: defaultCurrency },
    totalTax: { amount: "0.00", currencyCode: defaultCurrency },
    totalShipping: { amount: "20.00", currencyCode: defaultCurrency },
    currencyCode: defaultCurrency,
    lineItems: [
      {
        id: "ord-demo-000-line-1",
        productId: adhdProduct.id,
        productTitle: adhdProduct.title,
        variantId: adhdVariant.id,
        variantTitle: adhdVariant.title,
        quantity: 1,
        unitPrice: adhdVariant.price,
        totalPrice: { amount: "399.00", currencyCode: defaultCurrency },
        image: adhdProduct.featuredImage,
      },
    ],
    shippingAddress: demoAddress,
    billingAddress: demoAddress,
    shippingMethod: shippingMethods[1],
    customerId: "user-demo",
    appliedCoupons: [],
    loyaltyDelta: 120,
    tracking: {
      carrier: "顺丰速运",
      trackingNumber: "SF0987654321",
    },
  },
];
