import { thisYear } from "./mock-shared";
import type { Order } from "./types";
import { products } from "./mock-products";
import { demoAddress } from "./mock-account";
import {
  shippingMethods,
  defaultCurrency,
  welcomeAppliedCoupon,
} from "./mock-checkout";

const adhdProduct = products.find(
  (product) => product.id === "prod-adhd-medication",
)!;
const omega3Product = products.find((product) => product.id === "prod-omega3")!;
const probioticsProduct = products.find(
  (product) => product.id === "prod-probiotics",
)!;
const coq10Product = products.find((product) => product.id === "prod-coq10")!;

const adhdVariant = adhdProduct.variants[0]!;
const omega3Variant = omega3Product.variants[0]!;
const probioticsVariant = probioticsProduct.variants[0]!;
const coq10Variant = coq10Product.variants[0]!;

export const orders: Order[] = [
  {
    id: "ord-demo-003",
    number: "ORD-00003",
    status: "pending",
    financialStatus: "pending",
    fulfillmentStatus: "unfulfilled",
    createdAt: `${thisYear}-05-02T09:05:00.000Z`,
    updatedAt: `${thisYear}-05-02T09:05:00.000Z`,
    subtotalPrice: { amount: "158.00", currencyCode: defaultCurrency },
    totalPrice: { amount: "1608.00", currencyCode: defaultCurrency },
    totalTax: { amount: "0.00", currencyCode: defaultCurrency },
    totalShipping: { amount: "1450.00", currencyCode: defaultCurrency },
    currencyCode: defaultCurrency,
    lineItems: [
      {
        id: "ord-demo-003-line-1",
        productId: omega3Product.id,
        productTitle: omega3Product.title,
        variantId: omega3Variant.id,
        variantTitle: omega3Variant.title,
        quantity: 1,
        unitPrice: omega3Variant.price,
        totalPrice: { amount: "158.00", currencyCode: defaultCurrency },
        image: omega3Product.featuredImage,
      },
    ],
    shippingAddress: demoAddress,
    billingAddress: demoAddress,
    shippingMethod: shippingMethods[0],
    customerId: "user-demo",
    appliedCoupons: [],
    loyaltyDelta: 60,
  },
  {
    id: "ord-demo-002",
    number: "ORD-00002",
    status: "processing",
    financialStatus: "paid",
    fulfillmentStatus: "unfulfilled",
    createdAt: `${thisYear}-04-27T14:12:00.000Z`,
    updatedAt: `${thisYear}-04-27T14:20:00.000Z`,
    processedAt: `${thisYear}-04-27T14:15:00.000Z`,
    subtotalPrice: { amount: "399.00", currencyCode: defaultCurrency },
    totalPrice: { amount: "2199.00", currencyCode: defaultCurrency },
    totalTax: { amount: "0.00", currencyCode: defaultCurrency },
    totalShipping: { amount: "1800.00", currencyCode: defaultCurrency },
    currencyCode: defaultCurrency,
    lineItems: [
      {
        id: "ord-demo-002-line-1",
        productId: adhdProduct.id,
        productTitle: adhdProduct.title,
        variantId: adhdVariant.id,
        variantTitle: adhdVariant.title,
        quantity: 1,
        unitPrice: adhdVariant.price,
        totalPrice: { amount: "399.00", currencyCode: defaultCurrency },
        image: adhdProduct.featuredImage,
      },
    ],
    shippingAddress: demoAddress,
    billingAddress: demoAddress,
    shippingMethod: shippingMethods[1],
    customerId: "user-demo",
    appliedCoupons: [],
    loyaltyDelta: 120,
  },
  {
    id: "ord-demo-001",
    number: "ORD-00001",
    status: "fulfilled",
    financialStatus: "paid",
    fulfillmentStatus: "fulfilled",
    createdAt: `${thisYear}-04-16T08:12:00.000Z`,
    updatedAt: `${thisYear}-04-18T12:30:00.000Z`,
    processedAt: `${thisYear}-04-16T08:15:00.000Z`,
    fulfilledAt: `${thisYear}-04-18T11:40:00.000Z`,
    subtotalPrice: { amount: "454.00", currencyCode: defaultCurrency },
    totalPrice: { amount: "1858.60", currencyCode: defaultCurrency },
    totalTax: { amount: "0.00", currencyCode: defaultCurrency },
    totalShipping: { amount: "1450.00", currencyCode: defaultCurrency },
    currencyCode: defaultCurrency,
    lineItems: [
      {
        id: "ord-demo-001-line-1",
        productId: omega3Product.id,
        productTitle: omega3Product.title,
        variantId: omega3Variant.id,
        variantTitle: omega3Variant.title,
        quantity: 1,
        unitPrice: omega3Variant.price,
        totalPrice: { amount: "158.00", currencyCode: defaultCurrency },
        image: omega3Product.featuredImage,
      },
      {
        id: "ord-demo-001-line-2",
        productId: probioticsProduct.id,
        productTitle: probioticsProduct.title,
        variantId: probioticsVariant.id,
        variantTitle: probioticsVariant.title,
        quantity: 1,
        unitPrice: probioticsVariant.price,
        totalPrice: { amount: "128.00", currencyCode: defaultCurrency },
        image: probioticsProduct.featuredImage,
      },
      {
        id: "ord-demo-001-line-3",
        productId: coq10Product.id,
        productTitle: coq10Product.title,
        variantId: coq10Variant.id,
        variantTitle: coq10Variant.title,
        quantity: 1,
        unitPrice: coq10Variant.price,
        totalPrice: { amount: "168.00", currencyCode: defaultCurrency },
        image: coq10Product.featuredImage,
      },
    ],
    shippingAddress: demoAddress,
    billingAddress: demoAddress,
    shippingMethod: shippingMethods[0],
    customerId: "user-demo",
    appliedCoupons: [welcomeAppliedCoupon],
    loyaltyDelta: 300,
    tracking: {
      carrier: "顺丰速运",
      trackingNumber: "SF1234567890",
    },
  },
  {
    id: "ord-demo-000",
    number: "ORD-00000",
    status: "fulfilled",
    financialStatus: "paid",
    fulfillmentStatus: "fulfilled",
    createdAt: `${thisYear}-03-22T10:05:00.000Z`,
    updatedAt: `${thisYear}-03-24T18:30:00.000Z`,
    processedAt: `${thisYear}-03-22T10:08:00.000Z`,
    fulfilledAt: `${thisYear}-03-24T16:40:00.000Z`,
    subtotalPrice: { amount: "399.00", currencyCode: defaultCurrency },
    totalPrice: { amount: "2199.00", currencyCode: defaultCurrency },
    totalTax: { amount: "0.00", currencyCode: defaultCurrency },
    totalShipping: { amount: "1800.00", currencyCode: defaultCurrency },
    currencyCode: defaultCurrency,
    lineItems: [
      {
        id: "ord-demo-000-line-1",
        productId: adhdProduct.id,
        productTitle: adhdProduct.title,
        variantId: adhdVariant.id,
        variantTitle: adhdVariant.title,
        quantity: 1,
        unitPrice: adhdVariant.price,
        totalPrice: { amount: "399.00", currencyCode: defaultCurrency },
        image: adhdProduct.featuredImage,
      },
    ],
    shippingAddress: demoAddress,
    billingAddress: demoAddress,
    shippingMethod: shippingMethods[1],
    customerId: "user-demo",
    appliedCoupons: [],
    loyaltyDelta: 120,
    tracking: {
      carrier: "顺丰速运",
      trackingNumber: "SF0987654321",
    },
  },
];
