export type PhoneDialCodeOption = {
  code: string;
  country: string;
  iso2: string;
};

export const PHONE_DIAL_CODE_OPTIONS: PhoneDialCodeOption[] = [
  { code: "+1", country: "United States & Canada", iso2: "US" },
  { code: "+7", country: "Russia", iso2: "RU" },
  { code: "+20", country: "Egypt", iso2: "EG" },
  { code: "+27", country: "South Africa", iso2: "ZA" },
  { code: "+30", country: "Greece", iso2: "GR" },
  { code: "+31", country: "Netherlands", iso2: "NL" },
  { code: "+32", country: "Belgium", iso2: "BE" },
  { code: "+33", country: "France", iso2: "FR" },
  { code: "+34", country: "Spain", iso2: "ES" },
  { code: "+36", country: "Hungary", iso2: "HU" },
  { code: "+39", country: "Italy", iso2: "IT" },
  { code: "+40", country: "Romania", iso2: "RO" },
  { code: "+41", country: "Switzerland", iso2: "CH" },
  { code: "+43", country: "Austria", iso2: "AT" },
  { code: "+44", country: "United Kingdom", iso2: "GB" },
  { code: "+45", country: "Denmark", iso2: "DK" },
  { code: "+46", country: "Sweden", iso2: "SE" },
  { code: "+47", country: "Norway", iso2: "NO" },
  { code: "+48", country: "Poland", iso2: "PL" },
  { code: "+49", country: "Germany", iso2: "DE" },
  { code: "+52", country: "Mexico", iso2: "MX" },
  { code: "+54", country: "Argentina", iso2: "AR" },
  { code: "+55", country: "Brazil", iso2: "BR" },
  { code: "+56", country: "Chile", iso2: "CL" },
  { code: "+57", country: "Colombia", iso2: "CO" },
  { code: "+58", country: "Venezuela", iso2: "VE" },
  { code: "+60", country: "Malaysia", iso2: "MY" },
  { code: "+61", country: "Australia", iso2: "AU" },
  { code: "+62", country: "Indonesia", iso2: "ID" },
  { code: "+63", country: "Philippines", iso2: "PH" },
  { code: "+64", country: "New Zealand", iso2: "NZ" },
  { code: "+65", country: "Singapore", iso2: "SG" },
  { code: "+66", country: "Thailand", iso2: "TH" },
  { code: "+81", country: "Japan", iso2: "JP" },
  { code: "+82", country: "South Korea", iso2: "KR" },
  { code: "+84", country: "Vietnam", iso2: "VN" },
  { code: "+86", country: "China", iso2: "CN" },
  { code: "+852", country: "Hong Kong", iso2: "HK" },
  { code: "+853", country: "Macau", iso2: "MO" },
  { code: "+855", country: "Cambodia", iso2: "KH" },
  { code: "+856", country: "Laos", iso2: "LA" },
  { code: "+880", country: "Bangladesh", iso2: "BD" },
  { code: "+886", country: "Taiwan", iso2: "TW" },
  { code: "+90", country: "Turkey", iso2: "TR" },
  { code: "+91", country: "India", iso2: "IN" },
  { code: "+92", country: "Pakistan", iso2: "PK" },
  { code: "+93", country: "Afghanistan", iso2: "AF" },
  { code: "+94", country: "Sri Lanka", iso2: "LK" },
  { code: "+95", country: "Myanmar", iso2: "MM" },
  { code: "+98", country: "Iran", iso2: "IR" },
  { code: "+971", country: "United Arab Emirates", iso2: "AE" },
  { code: "+972", country: "Israel", iso2: "IL" },
  { code: "+973", country: "Bahrain", iso2: "BH" },
  { code: "+974", country: "Qatar", iso2: "QA" },
  { code: "+965", country: "Kuwait", iso2: "KW" },
  { code: "+966", country: "Saudi Arabia", iso2: "SA" },
  { code: "+968", country: "Oman", iso2: "OM" },
  { code: "+970", country: "Palestine", iso2: "PS" },
  { code: "+994", country: "Azerbaijan", iso2: "AZ" },
  { code: "+995", country: "Georgia", iso2: "GE" },
  { code: "+998", country: "Uzbekistan", iso2: "UZ" },
];
